project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "EDAV Crime: Is there any pattern in arrests by crime?"
  author:
    - Xinran She (xs2518)
    - Lu Liu (ll3721)
  repo-url: https://github.com/thisisliulu/Crime_USA
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


